[project]
name = "social-inference"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "numpy>=2.2.4",
    "requests>=2.32.3",
    "torch>=2.6.0",
]
